server:
    port: 5000

spring:
    mail:
        host: smtp.gmail.com
        port: 587
        username: ilyes.bourouba7@gmail.com
        password: ltrq ykku eppa gfbm
        properties:
            mail:
                smtp:
                    ssl:
                        trust: smtp.gmail.com
                    auth: true
                    starttls:
                        enable: true
